/******************* 
@Purpose : Used for environment configuration
@Parameter : {API_URL, PORT}
@Author : INIC
******************/
module.exports = {
  APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  PORT: process.env.PORT,
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  LINKEDIN_CLIENT_ID: process.env.NEXT_PUBLIC_LINKEDIN_CLIENT_ID,
  FACEBOOK_APP_ID: process.env.NEXT_PUBLIC_FACEBOOK_APP_ID,
  AUTH_API_URL: process.env.NEXT_PUBLIC_AUTH_API_URL,
  ADMIN_API_URL: process.env.NEXT_PUBLIC_ADMIN_API_URL,
  USER_API_URL: process.env.NEXT_PUBLIC_USER_API_URL,
  IMAGE_URL: process.env.NEXT_PUBLIC_IMAGE_URL,
  IMAGE_API_URL: process.env.NEXT_PUBLIC_IMAGE_API_URL,
  PUBLIC_PROFILE_URL: process.env.NEXT_PUBLIC_PROFILE_URL,
  GROWTH_MODEL_API_URL: process.env.NEXT_PUBLIC_GROWTH_MODEL_API_URL,
  PAYMENT_API_URL: process.env.NEXT_PUBLIC_PAYMENT_API_URL,
  STRIPE_PUBLIC_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY,
  NOTIFICATION_API_URL: process.env.NEXT_PUBLIC_NOTIFICATION_API_URL,
  CHAT_API_URL: process.env.NEXT_PUBLIC_CHAT_API_URL,
  PEER_PRODUCER_URL: process.env.NEXT_PUBLIC_PEER_PRODUCER_PORTAL,
  SOCKET_END_POINT: process.env.NEXT_PUBLIC_SOCKET_BASE_URL,
  YCHAT_SOCKET_END_POINT: process.env.NEXT_PUBLIC_YCHAT_SOCKET_BASE_URL,
  DOMAIN: process.env.NEXT_PUBLIC_DOMAIN,
  CONTENTS_API_URL: process.env.NEXT_PUBLIC_CONTENTS_API_URL,
  POST_API_URL: process.env.NEXT_PUBLIC_POST_API_URL,
  GOOGLE_MAP_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY,
  LINKEDIN_API_URL: process.env.NEXT_PUBLIC_LINKEDIN_API_URL,
  CHAT_TEAM_ID: process.env.NEXT_PUBLIC_CHAT_TEAM_ID,
  YMEET_API: process.env.NEXT_PUBLIC_YMEET_API,
  YLIMEET_API: process.env.NEXT_PUBLIC_YLIMEET_API,
  HARD_SKILLS_AREA_ID: process.env.NEXT_PUBLIC_HARD_SKILLS_AREA_ID,
  SOFT_SKILLS_AREA_ID: process.env.NEXT_PUBLIC_SOFT_SKILLS_AREA_ID,
  MINDSET_SKILLS_AREA_ID: process.env.NEXT_PUBLIC_MINDSET_SKILLS_AREA_ID,
  SEGMENT_SOURCE_KEY: process.env.NEXT_PUBLIC_SEGMENT_SOURCE_KEY,
};
