/******************* 
@purpose : Redux Action Types
@Author : INIC
******************/

// UI reducer types
export const SET_UI_KEY = "SET_UI_KEY";
export const SHOW_ALERT = "SHOW_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_MODALS = "TOGGLE_MODALS";
export const TOGGLE_LOADER = "TOGGLE_LOADER";
export const SHARE_MODAL = "SHARE_MODAL";
export const SKILL_ENDORSE_MODAL = "SKILL_ENDORSE_MODAL";
export const ARTICLE_MODAL = "ARTICLE_MODAL";
export const OTHER_CONNECTION = "OTHER_CONNECTION";
export const VIEW_CERTIFICATE = "VIEW_CERTIFICATE";
export const UPLOAD_COURSE_PDF = "UPLOAD_COURSE_PDF";

// Auth reducer types
export const SET_TOKEN = "SET_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN";

export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const REMOVE_REFRESH_TOKEN = "REMOVE_REFRESH_TOKEN";

export const SET_VERIFY_TYPE = "SET_VERIFY_TYPE";
export const REMOVE_VERIFY_TYPE = "REMOVE_VERIFY_TYPE";

export const LOGGED_SUCCEEDED = "LOGGED_SUCCEEDED";
export const ALLOW_SIGNUP = "ALLOW_SIGNUP";

// User reducer types
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_YLIWAY_USER_CERTIFICATE = "SET_YLIWAY_USER_CERTIFICATE";
export const SET_MONITISATION_FEATURE_LIST = "SET_MONITISATION_FEATURE_LIST";
export const SET_MONITISATION_PLAN_LIST = "SET_MONITISATION_PLAN_LIST";
export const SET_MONITISATION_PLAN_DETAILS = "SET_MONITISATION_PLAN_DETAILS";
export const SET_LAST_PURCHASED_PLAN_DETAILS =
  "SET_LAST_PURCHASED_PLAN_DETAILS";

export const SET_MONITISATION_PURCHASED_FEATURE_LIST =
  "SET_MONITISATION_PURCHASED_FEATURE_LIST";
export const SET_USER_FULL_INFO = "SET_USER_FULL_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const SET_CHECK_PENDING_REQUEST = "SET_CHECK_PENDING_REQUEST";
export const SET_ENTITY_DETAILS = "SET_ENTITY_DETAILS";

// Testimonial reducer types
export const SET_TESTIMONIAL_INFO = "SET_TESTIMONIAL_INFO";
// Faq reducer types
export const SET_FAQ_INFO = "SET_FAQ_INFO";
export const SET_CERTIFICATE_INFO = "SET_CERTIFICATE_INFO";
export const SET_ROLE_INFO = "SET_ROLE_INFO";
//about us reducer type
export const SET_ABOUTUS_INFO = "SET_ABOUTUS_INFO";
export const SET_ABOUTEACHER_INFO = "SET_ABOUTEACHER_INFO";
export const SET_ABOUT_INSTITUTE_INFO = "SET_ABOUT_INSTITUTE_INFO";
export const SET_WORKWITHUS_INFO = "SET_WORKWITHUS_INFO";

//Privacy reducer types
export const SET_PRIVACY_INFO = "SET_PRIVACY_INFO";

//Terms and Condiction reducer types
export const SET_TERMS_INFO = "SET_TERMS_INFO";

//Cookie reducer types
export const SET_COOKIES_INFO = "SET_COOKIES_INFO";

// Invester Relation types
export const SET_INVEST_REL_INFO = "SET_INVEST_REL_INFO";

//Cookie reducer types
export const SET_BRAND_INFO = "SET_BRAND_INFO";

export const SET_CMS_STATUS_LIST = "SET_CMS_STATUS_LIST";

// Experiece Action Types
export const SET_CURRENT_USER_EXPERIENCE = "SET_CURRENT_USER_EXPERIENCE";
export const UNSET_CURRENT_USER_EXPERIENCE = "UNSET_CURRENT_USER_EXPERIENCE";
export const ADD_CURRENT_USER_EXPERIENCE = "ADD_CURRENT_USER_EXPERIENCE";
export const UPDATE_CURRENT_USER_EXPERIENCE = "UPDATE_CURRENT_USER_EXPERIENCE";
export const DELETE_CURRENT_USER_EXPERIENCE = "DELETE_CURRENT_USER_EXPERIENCE";
export const GET_LERNING_INSTITUTE_LIST = "GET_LERNING_INSTITUTE_LIST";
export const GET_USER_COMPANY_LIST = "GET_USER_COMPANY_LIST";
export const GET_USER_ORGANIZATION_LIST = "GET_USER_ORGANIZATION_LIST";
export const GET_EXPERIENCE_LIST = "GET_EXPERIENCE_LIST";

// User Profile Description Action Types
export const UPDATE_CURRENT_USER_INFO = "UPDATE_CURRENT_USER_INFO";
export const SET_CURRENT_USER_COUNT_DATA = "SET_CURRENT_USER_COUNT_DATA";

// Activity Action Types
export const SET_CURRENT_USER_ACTIVITY = "SET_CURRENT_USER_ACTIVITY";
export const SET_CURRENT_USER_ACTIVITY_FOLLOWER_COUNT =
  "SET_CURRENT_USER_ACTIVITY_FOLLOWER_COUNT";
export const UNSET_CURRENT_USER_ACTIVITY = "UNSET_CURRENT_USER_ACTIVITY";

// Certification Action Types
export const SET_CURRENT_USER_CERTIFICATION = "SET_CURRENT_USER_CERTIFICATION";
export const ADD_CURRENT_USER_CERTIFICATION = "ADD_CURRENT_USER_CERTIFICATION";
export const UPDATE_CURRENT_USER_CERTIFICATION =
  "UPDATE_CURRENT_USER_CERTIFICATION";
export const DELETE_CURRENT_USER_CERTIFICATION =
  "DELETE_CURRENT_USER_CERTIFICATION";
export const GET_CERTIFICATION_LIST = "GET_CERTIFICATION_LIST";

// Language Action Types
export const SET_CURRENT_USER_LANGUAGE = "SET_CURRENT_USER_LANGUAGE";
export const ADD_CURRENT_USER_LANGUAGE = "ADD_CURRENT_USER_LANGUAGE";
export const UPDATE_CURRENT_USER_LANGUAGE = "UPDATE_CURRENT_USER_LANGUAGE";
export const DELETE_CURRENT_USER_LANGUAGE = "DELETE_CURRENT_USER_LANGUAGE";

// Group reducer types
export const GET_GROUPS_LIST = "GET_GROUPS_LIST";
export const GET_GROUP_DETAILS = "GET_GROUP_DETAILS";
export const GET_GROUPS_JOINED_LIST = "GET_GROUPS_JOINED_LIST";
export const GET_GROUPS_INVITE_RECEIVED = "GET_GROUPS_INVITE_RECEIVED";
export const GROUPS_INVITE_ACTION = "GROUPS_INVITE_ACTION";
export const GET_GROUPS_CONNECTION_LIST = "GET_GROUPS_CONNECTION_LIST";
export const GROUPS_UNFOLLOW = "GROUPS_UNFOLLOW";
export const GROUPS_SEARCH_UNFOLLOW = "GROUPS_SEARCH_UNFOLLOW";
export const MEMBER_DELETE = "MEMBER_DELETE";
export const GROUPS_MUTE_UNMUTE = "GROUPS_MUTE_UNMUTE";
export const MYGROUPS_MUTE_UNMUTE = "MYGROUPS_MUTE_UNMUTE";
export const GROUPS_SEARCH_MUTE_UNMUTE = "GROUPS_SEARCH_MUTE_UNMUTE";
export const GROUPS_DELETE = "GROUPS_DELETE";
export const CLEAR_MYGROUP_DATA = "CLEAR_MYGROUP_DATA";
export const CLEAR_GROUP_DATA = "CLEAR_GROUP_DATA";
export const GROUPS_SEARCH = "GROUPS_SEARCH";
export const REQUEST_RECEIVED = "REQUEST_RECEIVED";
export const CLEAR_GROUP_SEARCH_DATA = "CLEAR_GROUP_SEARCH_DATA";
export const GROUP_MEMBERS_LIST = "GROUP_MEMBERS_LIST";
export const SET_GROUP_ID_TO_DELETE = "SET_GROUP_ID_TO_DELETE";
export const REPORT_POST_ID = "REPORT_POST_ID";
export const SET_MEMBER_DETAILS = "SET_MEMBER_DETAILS";
export const PROFILE_GROUPS_LIST = "PROFILE_GROUPS_LIST";
export const GET_ALL_GROUPS_LIST = "GET_ALL_GROUPS_LIST";
export const GET_REQUESTED_GROUPS_LIST = "GET_REQUESTED_GROUPS_LIST";
export const GET_WAITING_GROUPS_LIST = "GET_WAITING_GROUPS_LIST";
export const SET_MYGROUP_DETAILS = "SET_MYGROUP_DETAILS";
export const CLEAR_GROUPS_CONNECTION_LIST = "CLEAR_GROUPS_CONNECTION_LIST";

// Education Action Types
export const SET_CURRENT_USER_EDUCATION = "SET_CURRENT_USER_EDUCATION";
export const ADD_CURRENT_USER_EDUCATION = "ADD_CURRENT_USER_EDUCATION";
export const UPDATE_CURRENT_USER_EDUCATION = "UPDATE_CURRENT_USER_EDUCATION";
export const DELETE_CURRENT_USER_EDUCATION = "DELETE_CURRENT_USER_EDUCATION";
export const GET_EDUCATION_LIST = "GET_EDUCATION_LIST";

//Post Action Types
export const SET_POST_ADD = "SET_POST_ADD";
export const SET_POST_LISTING = "SET_POST_LISTING";
export const SET_POST_IMAGE = "SET_POST_IMAGE";
export const SET_POST_IMAGE_ALTERNATIVE_TEXT = "SET_POST_IMAGE_ALTERNATIVE_TEXT";
export const SET_IMAGE_TAGGED_USER_DARA = "SET_IMAGE_TAGGED_USER_DARA";
export const SET_POST_VIDEO = "SET_POST_VIDEO";
export const SET_POST_DOCUMENT = "SET_POST_DOCUMENT";
export const SET_SPEAKER = "SET_SPEAKER";
export const CLEAR_ADD_POST_DATA = "CLEAR_ADD_POST_DATA";
export const SET_COMMENT_LIST = "SET_COMMENT_LIST";
export const SET_COMMENT_REPLY_LIST = "SET_COMMENT_REPLY_LIST";
export const SET_POST_LIKE_DATA = "SET_POST_LIKE_DATA";
export const SET_GROUP_ID_POST = "SET_GROUP_ID_POST";
export const SET_SINGLE_POST_DATA = "SET_SINGLE_POST_DATA";
export const CHANGE_POST_GM_STATUS = "CHANGE_POST_GM_STATUS";
export const UPDATE_LIKE_COUNT = "UPDATE_LIKE_COUNT";
export const UPDATE_COMMENT_COUNT = "UPDATE_COMMENT_COUNT";
export const UPDATE_REPLY_COMMENT_COUNT = "UPDATE_REPLY_COMMENT_COUNT";
export const SET_COMMENT_DATA = "SET_COMMENT_DATA";

// Connections Action Types
export const GET_PEOPLE_YOU_MAY_KNOW_LIST = "GET_PEOPLE_YOU_MAY_KNOW_LIST";
export const UPDATE_PEOPLE_YOU_MAY_KNOW_LIST_USER =
  "UPDATE_PEOPLE_YOU_MAY_KNOW_LIST_USER";
export const GET_PENDING_CONNECTIONS_LIST = "GET_PENDING_CONNECTIONS_LIST";
export const GET_SENT_CONNECTIONS_LIST = "GET_SENT_CONNECTIONS_LIST";
export const GET_MY_CONNECTIONS_LIST = "GET_MY_CONNECTIONS_LIST";
export const GET_PEOPLE_VIEWED_LIST = "GET_PEOPLE_VIEWED_LIST";
export const ADD_TO_SENT_CONNECTION_LIST = "ADD_TO_SENT_CONNECTION_LIST";
export const REMOVE_FROM_PEOPLE_YOU_MAY_KNOW =
  "REMOVE_FROM_PEOPLE_YOU_MAY_KNOW";
export const REMOVE_FROM_MY_CONNECTION = "REMOVE_FROM_MY_CONNECTION";
export const REMOVE_FROM_SENT_CONNECTION = "REMOVE_FROM_SENT_CONNECTION";
export const REMOVE_FROM_PENDING_CONNECTION = "REMOVE_FROM_PENDING_CONNECTION";
export const POST_TYPE = "POST_TYPE";
export const CREATE_POLL = "CREATE_POLL";
export const EDIT_CREATE_POLL = "EDIT_CREATE_POLL";
export const EDIT_DASHBOARD_POST = "EDIT_DASHBOARD_POST";
export const GET_FOLLOWERS_LIST = "GET_FOLLOWERS_LIST";
export const GET_FOLLOWINGS_LIST = "GET_FOLLOWINGS_LIST";
export const REMOVE_USER_FROM_FOLLOWINGS = "REMOVE_USER_FROM_FOLLOWINGS";
export const GET_MY_GROWTH_CONNECTIONS_LIST = "GET_MY_GROWTH_CONNECTIONS_LIST";
export const SET_GROWTH_PARTNER_LIST = "SET_GROWTH_PARTNER_LIST";
export const SET_GROWTH_PARTNER_ACTIVITY_LIST =
  "SET_GROWTH_PARTNER_ACTIVITY_LIST";
export const SET_SEARCHED_GROWTH_PARTNER_LIST =
  "SET_SEARCHED_GROWTH_PARTNER_LIST";

// Article
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const SET_ARTICLE_LIST = "SET_ARTICLE_LIST";
export const SET_ARTICLE_DATA = "SET_ARTICLE_DATA";
export const UPDATE_ARTICLE_LIKE_COUNT = "UPDATE_ARTICLE_LIKE_COUNT";

// My Account Settings Action Types
export const SUSPEND_ACCOUNT = "SUSPEND_ACCOUNT";
export const CLOSE_ACCOUNT = "CLOSE_ACCOUNT";
export const SET_PREFERENCES = "SET_PREFERENCES";
export const SET_LI_ROLES = "SET_LI_ROLES";
export const CLEAR_STATE = "CLEAR_STATE";
export const SET_NUMBERS = "SET_NUMBERS";

// Plan Action Types
export const SET_PLAN_DATA = "SET_NUMBERS";
export const VOTE_CLICK_DATA = "VOTE_CLICK_DATA";
export const ADD_CARDS = "ADD_CARDS";

//Growth Model
export const SET_GROWTHMODEL_SELECTED_SKILLS =
  "SET_GROWTHMODEL_SELECTED_SKILLS";
export const SET_GROWTHMODEL = "SET_GROWTHMODEL";
export const SET_GROWTHMODEL_BLANK_RES = "SET_GROWTHMODEL_BLANK_RES";
export const SET_STEP_GM = "SET_STEP_GM";
export const UPDATE_GROWTHMODEL = "UPDATE_GROWTHMODEL";
export const SET_GROWTH_PROJECT = "SET_GROWTH_PROJECT";
export const SET_GROWTH_PROFESSION = "SET_GROWTH_PROFESSION";
export const SET_GROWTHMODEL_ACTIVITIES = "SET_GROWTHMODEL_ACTIVITIES";
export const ADD_GROWTHMODEL_ACTIVITY = "ADD_GROWTHMODEL_ACTIVITY";
export const REMOVE_GROWTHMODEL_ACTIVITY = "REMOVE_GROWTHMODEL_ACTIVITY";
export const GROWTH_MODEL_ACTIVITIES_STATUS = "GROWTH_MODEL_ACTIVITIES_STATUS";
export const ADD_GROWTH_MODEL_ACTIVITIES = "ADD_GROWTH_MODEL_ACTIVITIES";
export const SET_BLOCK_ID = "SET_BLOCK_ID";
export const ACTIVITY_LIST_CLEARDATA = "ACTIVITY_LIST_CLEARDATA";
export const TRAINING_ROOM_LIST = "TRAINING_ROOM_LIST";
export const EVENT_LIST = "EVENT_LIST";
export const WEBINAR_LIST = "WEBINAR_LIST";
export const MASTER_CLASS_LIST = "MASTER_CLASS_LIST";
export const COACHING_ROOM_LIST = "COACHING_ROOM_LIST";
export const BNR_LIST = "BNR_LIST";
export const HARD_SKILL_LIST = "HARD_SKILL_LIST";
export const SOFT_SKILL_LIST = "SOFT_SKILL_LIST";
export const MINDSET_LIST = "MINDSET_LIST";
export const TRACTION_LIST = "TRACTION_LIST";
export const DISTRIBUTION_LIST = "DISTRIBUTION_LIST";
export const SUPPORT_LIST = "SUPPORT_LIST";
export const SET_BLOCK_PAYLOAD = "SET_BLOCK_PAYLOAD";
export const SET_SOFTBLOCK_PAYLOAD = "SET_SOFTBLOCK_PAYLOAD";
export const SET_TRACTION_PAYLOAD = "SET_TRACTION_PAYLOAD";
export const SET_SUPPORT_PAYLOAD = "SET_SUPPORT_PAYLOAD";
export const SET_MINDSET_PAYLOAD = "SET_MINDSET_PAYLOAD";
export const SET_DISTRIBUTION_PAYLOAD = "SET_DISTRIBUTION_PAYLOAD";
export const CLEAR_SKILL_TYPE = "CLEAR_SKILL_TYPE";
export const SET_RECENT_ADD_TO_GM = "SET_RECENT_ADD_TO_GM";
export const MOST_FOLLOWED_CONTENT = "MOST_FOLLOWED_CONTENT";
export const STORE_PROFESSION_STEP_ONE = "STORE_PROFESSION_STEP_ONE";
export const STORE_JOBTYPE_STEP_ONE = "STORE_JOBTYPE_STEP_ONE";
export const SET_GM_DEPARTMENT_LIST = "SET_GM_DEPARTMENT_LIST";
export const SET_GM_PROFESSION_LIST = "SET_GM_PROFESSION_LIST";
export const CLEAR_SOFTSKILL_REDUCER = "CLEAR_SOFTSKILL_REDUCER";
export const CLEAR_MINDSET_REDUCER = "CLEAR_MINDSET_REDUCER";
export const CLEAR_TRACTION_REDUCER = "CLEAR_TRACTION_REDUCER";
export const CLEAR_HARDSKILLS_REDUCER = "CLEAR_HARDSKILLS_REDUCER";
export const CLEAR_DISTRIBUTION_REDUCER = "CLEAR_DISTRIBUTION_REDUCER";
export const CLEAR_SUPPORT_REDUCER = "CLEAR_SUPPORT_REDUCER";
export const STORE_NEWS_FEED_GM_RESPONSE = "STORE_NEWS_FEED_GM_RESPONSE";
export const BLOCK_FLAG_DATA = "BLOCK_FLAG_DATA";
export const CLEAR_SKILL_DATA = "CLEAR_SKILL_DATA";

//Training Rooms Types
export const SET_ROOM_CREATE = "ROOM_CREATE";
export const SET_ROOM_LIST = "ROOM_LIST";
export const SET_ROOM_LIST_LOADER = "SET_ROOM_LIST_LOADER";
export const SET_ROOM_DETAILS = "ROOM_DETAILS";
export const SET_BANNER_IMAGE = "SET_BANNER_IMAGE";
export const SET_PREVIEW_VIDEO = "SET_PREVIEW_VIDEO";
export const SET_ROOM_DETAILS_CLEAR = "SET_ROOM_DETAILS_CLEAR";
export const SET_BLOCK_PAYLOAD_DETAILS_CLEAR =
  "SET_BLOCK_PAYLOAD_DETAILS_CLEAR";

//Yli Meet Meeting Types
export const SET_YLIMEET_INSTANT_MEETING_DETAILS = "YLIMEET_INSTANT_MEETING_DETAILS";

//Language List Types
export const SET_LANGUAGE_LIST = "SET_LANGUAGE_LIST";
export const SET_CONFIGURATION = "SET_CONFIGURATION";

// Visibilitiy
export const GET_PROFILE_OPTIONS = "GET_PROFILE_OPTIONS";
export const GET_STORY_OPTIONS = "GET_STORY_OPTIONS";
export const GET_PUBLIC_PROFILE = "GET_PUBLIC_PROFILE";
export const GET_LINKS_OPTIONS = "GET_LINKS_OPTIONS";
export const GET_LASTNAME_OPTIONS = "GET_LASTNAME_OPTIONS";
export const GET_CONNECTION_OPTIONS = "GET_CONNECTION_OPTIONS";
export const GET_TAGS_OPTIONS = "GET_TAGS_OPTIONS";
export const GET_BLOCK_USER_LIST = "GET_BLOCK_USER_LIST";

//Communication

export const GET_COMMUNICATION = "GET_COMMUNICATION";

//Manage Activity
export const GET_ACTIVITY_DATA = "GET_ACTIVITY_DATA";

//Blog
export const SET_BLOG_LISTING = "SET_BLOG_LISTING";
export const GET_BLOG_DETAIL = "GET_BLOG_DETAIL";
export const GET_BLOG_READER = "GET_BLOG_READER";

//Search result
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";
export const RECENT_SEARCH_LIST = "RECENT_SEARCH_LIST";
export const CLEAR_SEARCH_LIST = "CLEAR_SEARCH_LIST";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_SEARCHED_USER_LIST = "SET_SEARCHED_USER_LIST";

// Courses
// Courses
export const SET_COURSES = "SET_COURSES";
export const SET_QUIZ_QUESTIONS = "SET_QUIZ_QUESTIONS";
export const SET_SINGLE_QUIZ_QUESTIONS = "SET_SINGLE_QUIZ_QUESTIONS";
export const QUIZ_QUESTIONS_LIST = "QUIZ_QUESTIONS_LIST";
export const QUIZ_ANSWERS_LIST = "QUIZ_ANSWERS_LIST";
export const QUIZ_QUES_CLEAR = "QUIZ_QUES_CLEAR";
export const PRACTICAL_TEST_QUESTIONS_LIST = "PRACTICAL_TEST_QUESTIONS_LIST";
export const PRACTICAL_TEST_ANSWERS_LIST = "PRACTICAL_TEST_ANSWERS_LIST";
export const MY_LEARNING_LIST = "MY_LEARNING_LIST";
export const SET_CERTIFICATE_DETAIL = "SET_CERTIFICATE_DETAIL";
export const MY_LEARNING_COURSE_LIST = "MY_LEARNING_COURSE_LIST";
export const MY_LEARNING_TRAININGROOM_LIST = "MY_LEARNING_TRAININGROOM_LIST";
export const MY_LEARNING_EVENT_LIST = "MY_LEARNING_EVENT_LIST";
export const MY_LEARNING_WEBINAR_LIST = "MY_LEARNING_WEBINAR_LIST";
export const MY_LEARNING_COACHINGROOM_LIST = "MY_LEARNING_COACHINGROOM_LIST";
export const MY_LEARNING_BNR_LIST = "MY_LEARNING_BNR_LIST";
export const MY_LEARNING_MASTERCLASS_LIST = "MY_LEARNING_MASTERCLASS_LIST";
export const MY_LEARNING_WELCOME_ROOM = "MY_LEARNING_WELCOME_ROOM";
export const SET_COURSE_DETAIL = "SET_COURSE_DETAIL";
export const SET_COURSE_PLAYLIST = "SET_COURSE_PLAYLIST";

// Subscription
export const SET_SUBSCRIPTION_LISTING = "SET_SUBSCRIPTION_LISTING";

// Become teacher
export const GET_TOPIC = "GET_TOPIC";
// Skill
export const SET_SKILL_TYPE = "SET_SKILL_TYPE";
export const SET_SKILL_AREA = "SET_SKILL_AREA";
export const SET_SKILL_USERLIST = "SET_SKILL_USERLIST";
export const ADD_SKILLS_DATA = "ADD_SKILLS_DATA";
export const UPDATE_SKILLS_DATA = "UPDATE_SKILLS_DATA";
export const DELETE_SKILLS_DATA = "DELETE_SKILLS_DATA";
export const SKILLS_LIST = "SKILLS_LIST";
export const SKILLS_USER_LIST = "SKILLS_USER_LIST";
export const SKILLS_ENDORSE_LIST = "SKILLS_ENDORSE_LIST";
export const ACTIVITY_LIST_DATA = "ACTIVITY_LIST_DATA";
export const ACTIVITY_LIST_DATA_UPDATE = "ACTIVITY_LIST_DATA_UPDATE";
export const SAVE_ACTIVITY_CLEAR = "SAVE_ACTIVITY_CLEAR";
export const REQUEST_FOR_RECOMMENDATION = "REQUEST_FOR_RECOMMENDATION";
export const USER_HARD_SKILL_LIST = "USER_HARD_SKILL_LIST";
export const USER_SOFT_SKILL_LIST = "USER_SOFT_SKILL_LIST";
export const USER_MINDSET_SKILL_LIST = "USER_MINDSET_SKILL_LIST";

//notifications
export const SET_NOTIFICATION_LIST = "SET_NOTIFICATION_LIST";

//message
export const SET_CHANNEL_LIST = "SET_CHANNEL_LIST";
export const SET_UPDATE_CHANNEL_LIST = "SET_UPDATE_CHANNEL_LIST";
export const SET_CURRENT_CHANNEL_DETAILS = "SET_CURRENT_CHANNEL_DETAILS";
export const UPDATE_CHANNEL_DETAIL = "UPDATE_CHANNEL_DETAIL";
export const UPDATE_CURRENT_CHANNEL_DETAIL = "UPDATE_CURRENT_CHANNEL_DETAIL";
export const SET_SOCKET_CONNECTION_DETAILS = "SET_SOCKET_CONNECTION_DETAILS";
export const SET_YCHAT_SOCKET_CONNECTION_DETAILS =
  "SET_YCHAT_SOCKET_CONNECTION_DETAILS";
export const LAST_MESSAGE = "LAST_MESSAGE";
export const ONLINE_MEMBERS = "ONLINE_MEMBERS";
export const SET_JOINED_CHANNEL_REFETCH = "SET_JOINED_CHANNEL_REFETCH";
export const SET_JOINED_CHANNEL_LIST = "SET_JOINED_CHANNEL_LIST";
export const SET_MESSAGE_COUNT = "SET_MESSAGE_COUNT";
export const SET_SEND_MESSAGE = "SET_SEND_MESSAGE";

//Learning Institute
export const SET_INSTITUTE_DETAILS = "SET_INSTITUTE_DETAILS";
export const SET_LEARNING_INSTITUTE_SECTORS = "SET_LEARNING_INSTITUTE_SECTORS";
export const SET_ABOUT_INFO = "SET_ABOUT_INFO";
export const ABOUT_US_ADD_UPDATE = "ABOUT_US_ADD_UPDATE";
export const LEARNING_EVENTS_PAST = "LEARNING_EVENTS_PAST";
export const LEARNING_EVENTS_UPCOMING = "LEARNING_EVENTS_UPCOMING";
export const LEARNING_EVENTS = "LEARNING_EVENTS";
export const LEARNING_TRAINING = "LEARNING_TRAINING";
export const LEARNING_COACH = "LEARNING_COACH";
export const LEARNING_WEBINAR = "LEARNING_WEBINAR";
export const LEARNING_MASTERCLASS = "LEARNING_MASTERCLASS";

//Company
export const SET_COMPANY_DETAILS = "SET_COMPANY_DETAILS";

//Zoom
export const GET_ZOOM_DATA = "GET_ZOOM_DATA";
export const GET_ZOOM_CLIENT_DATA = "GET_ZOOM_CLIENT_DATA";
export const GET_MEDIA_DATA = "GET_MEDIA_DATA";
export const GET_RECORDING_DATA = "GET_RECORDING_DATA";
export const GET_ZOOM_CHAT_DATA = "GET_ZOOM_CHAT_DATA";
export const SET_ZOOM_DATA_CLEAR = "SET_ZOOM_DATA_CLEAR";

// Institute tabs
export const SET_PEOPLE_LIST = "SET_PEOPLE_LIST";
export const SET_PEOPLE_LIST_PAGE = "SET_PEOPLE_LIST_PAGE";
export const SET_FOLLOWER_LIST = "SET_FOLLOWER_LIST";
export const SET_FOLLOWER_LIST_PAGE = "SET_FOLLOWER_LIST_PAGE";
export const SET_INSTITUTE_HOME_DETAILS = "SET_INSTITUTE_HOME_DETAILS";
export const SET_LEARNING_INST_COURSES_LIST = "SET_LEARNING_INST_COURSES_LIST";
export const SET_LEARNING_INST_COURSES_LIST_OFFLINE =
  "SET_LEARNING_INST_COURSES_LIST_OFFLINE";
export const SET_LEARNING_INST_COURSES_LIST_ONLINE =
  "SET_LEARNING_INST_COURSES_LIST_ONLINE";
export const SET_FACULTY_LIST = "SET_FACULTY_LIST";
export const SET_LEARNING_DETAILS = "SET_LEARNING_DETAILS";

// job
export const SET_INSTITUTE_JOB_LIST = "SET_INSTITUTE_JOB_LIST";
export const SET_SUGGESTED_JOB_LIST = "SET_SUGGESTED_JOB_LIST";
export const UPDATE_OLD_SELECTED_JOB_ID = "UPDATE_OLD_SELECTED_JOB_ID";
export const SET_SUGGESTED_JOB_DETAIL = "SET_SUGGESTED_JOB_DETAIL";
export const SET_SUGGESTED_ACTIVITY_LIST = "SET_SUGGESTED_ACTIVITY_LIST";
export const SET_INSTITUTE_JOB_EVENT_LIST = "SET_INSTITUTE_JOB_EVENT_LIST";
export const SET_INSTITUTE_JOB_CANDIDATE_LIST =
  "SET_INSTITUTE_JOB_CANDIDATE_LIST";
export const SET_INSTITUTE_SINGLE_JOB_CANDIDATE_LIST =
  "SET_INSTITUTE_SINGLE_JOB_CANDIDATE_LIST";
export const SET_INSTITUTE_SINGLE_JOB_CANDIDATE_DETAIL =
  "SET_INSTITUTE_SINGLE_JOB_CANDIDATE_DETAIL";
export const SET_INSTITUTE_JOB_DETAIL = "SET_INSTITUTE_JOB_DETAIL";
export const SET_JOB_RENDER = "SET_JOB_RENDER";
//Articles
export const SET_PUBLISHED_ARTICLE_DATA = "SET_PUBLISHED_ARTICLE_DATA";
export const SET_SERVICES_LIST = "SET_SERVICES_LIST";
export const SET_USERS_LIST = "SET_USERS_LIST";
export const SET_PURCHASE_LIST = "SET_PURCHASE_LIST";

export const SET_STUDENT_FEEDBACK = "SET_STUDENT_FEEDBACK";

//growth
export const SET_GROWTH_ITEMS = "SET_GROWTH_ITEMS";
export const ADD_TO_GM_STATUS = "ADD_TO_GM_STATUS";
export const SET_AUTHOR_API_DETAIL = "SET_AUTHOR_API_DETAIL";
export const SET_ACTIVITY_TYPE_DETAIL = "SET_ACTIVITY_TYPE_DETAIL";
export const CLEAR_AUTHOR_NAMES = "CLEAR_AUTHOR_NAMES";
export const SKILL_DATA_STOREM = "SKILL_DATA_STOREM";
export const SKILL_DATA_STORESS = "SKILL_DATA_STORESS";
export const SKILL_DATA_STORET = "SKILL_DATA_STORET";
export const SKILL_DATA_STOREHS = "SKILL_DATA_STOREHS";
export const SKILL_DATA_STORESupp = "SKILL_DATA_STORESupp";
export const SKILL_DATA_STOREDist = "SKILL_DATA_STOREDist";
export const GM_STATUS_DATA = "GM_STATUS_DATA";
export const SET_SOFTSKILL_SKILL_TYPE = "SET_SOFTSKILL_SKILL_TYPE";
export const SET_HARDSKILL_SKILL_TYPE = "SET_HARDSKILL_SKILL_TYPE";
export const SET_TRACTIONSKILL_SKILL_TYPE = "SET_TRACTIONSKILL_SKILL_TYPE";
export const SET_MINDSETSKILL_SKILL_TYPE = "SET_MINDSETSKILL_SKILL_TYPE";
export const SET_DISTRIBUTIONSKILL_SKILL_TYPE =
  "SET_DISTRIBUTIONSKILL_SKILL_TYPE";
export const SET_SUPPORTSKILL_SKILL_TYPE = "SET_SUPPORTSKILL_SKILL_TYPE";

//Welcome Rooms
export const SET_WELCOME_ROOMS = "SET_WELCOME_ROOMS";

// Chat
export const CHAT_LISTING = "CHAT_LISTING";
export const MESSAGE_LISTING = "MESSAGE_LISTING";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const THREAD_MESSAGE_LISTING = "THREAD_MESSAGE_LISTING";
export const SEARCH_MESSAGE_USER = "SEARCH_MESSAGE_USER";
export const CONFIRM_DELETE_MESSAGE = "CONFIRM_DELETE_MESSAGE";
export const PRIVATE_CHANNEL_MEMBERS = "PRIVATE_CHANNEL_MEMBERS";

// Company
export const SET_ABOUT_INFO_CO = "SET_ABOUT_INFO_CO";
export const SET_COMPANY_DATA = "SET_COMPANY_DATA";
export const SET_COMPANY_HOME_DETAILS = "SET_COMPANY_HOME_DETAILS";
export const SET_FOLLOWER_LIST_PAGE_CO = "SET_FOLLOWER_LIST_PAGE_CO";
export const SET_FOLLOWER_LIST_CO = "SET_FOLLOWER_LIST_CO";
export const SET_PEOPLE_LIST_PAGE_CO = "SET_PEOPLE_LIST_PAGE_CO";
export const SET_PEOPLE_LIST_CO = "SET_PEOPLE_LIST_CO";
export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";

export const SET_SKILLS_LIST = "SET_SKILLS_LIST";

// Calendar
export const SET_CALENDAR_EVENT_LIST = "SET_CALENDAR_EVENT_LIST";
export const UPSERT_CALENDAR_EVENT = "UPSERT_CALENDAR_EVENT";
export const REMOVE_CALENDAR_EVENT = "REMOVE_CALENDAR_EVENT";
